version: '3.4'

services:
  salestatistics.web:
    image: ${DOCKER_REGISTRY-}salestatisticsweb
    build:
      context: .
      dockerfile: src/SaleStatistics.Web/Dockerfile
    depends_on:
    - redis
    environment:
      - RedisConnectionString=redis
      - Funda__Key=ac1b0b1572524640a0ecc54de453ea9f

  redis:
    image: redis