version: '3.4'

services:
  salestatistics.web:
    image: ${DOCKER_REGISTRY-}salestatisticsweb
    build:
      context: .
      dockerfile: src/SaleStatistics.Web/Dockerfile
    depends_on:
    - redis
    environment:
      - RedisConnectionString=redis

  redis:
    image: redis